---

- name: Install base packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
    force: yes
  with_items:
    - build-essential
    - acl
    - git
    - unzip
    - libpq-dev
    - python-dev
    - python-pip
    - python-virtualenv
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Ensure git repo is present
  git:
    repo: https://github.com/AngelaVargas/drscratchv3
    dest: /var/www/drscratchv3

- name: Install requirements
  pip:
    requirements: /var/www/drscratchv3/requirements.txt
    executable: /var/venv/bin/pip
