---

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: install mysql
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
  tags: packages

- name: ensure python packages are installed
  apt:
    name: "{{ item }}"
  with_items:
    - libmysqlclient
    - libmysqld-dev

- name: ensure mysql service is running
  service: name=mysql state=started enabled=yes

- name: create mysql app user
  mysql_user:
    name: "{{ mysql_db_user }}"
    host: localhost
    password: "{{ mysql_db_password }}"
    priv: "*.*:ALL"
    state: present

- name: create mysql app database
  mysql_db:
    name: "{{ mysql_db_name }}"
    owner: "{{ mysql_db_user }}"
  become: True
  become_user: mysql

- name: ensure database is created
  mysql_db: name={{ db_name }} state=present encoding=utf8

- name: ensure database is created
  become_user: "{{ mysql_db_user }}"

- name: ensure user has access to database
  become_user: "{{ mysql_db_user }}"
  mysql_user:
    db: "{{ mysql_db_name }}"





- name: ensure user has access to the database
  mysql_user: name={{ db_user }} password={{ db_password }} priv='{{ db_name }}.*:ALL' state=present



