# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-24 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_merge'),
        ('app', '0050_coder_img'),
    ]

    operations = [
    ]
